name: zcash-mini
version: master
summary: A minimal portable Zcash z-address generator for offline / paper wallets
description: |
  zcash-mini is a minimal, portable Zcash wallet generator in Go.

grade: devel
confinement: strict

apps:
  zcash-mini:
    command: zcash-mini

parts:
  zcash-mini:
    source: .
    plugin: go
    go-importpath: github.com/FiloSottile/zcash-mini
